name: Testes
on:
  pull_request

jobs:
  continuos-integration:
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Run install, build and test
        run: |
          npm install
          npm build
          npm test
